version: '3.9'

services:

  sm_postgres:
    image: postgres:13
    container_name: sm_postgres
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
    networks:
      freedom_net:
        ipv4_address: 172.16.110.2
    working_dir: /app
    environment:
      POSTGRES_DB: machine
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGPASSWORD: pass
    ports:
      - 5432:5432
  
  sm_nginx:
    image: nginx:latest
    container_name: sm_nginx
    restart: always
    networks:
      freedom_net:
        ipv4_address: 172.16.110.3
    volumes:
      - type: bind
        source: ./
        target: /app
      - ./deploy/docker-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./deploy/hosts:/etc/hosts
      - ./deploy/bashrc:/root/.bashrc
    ports:
      - 8000:80
  
  sm_frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sm_frontend
    volumes:
      - type: bind
        source: ./
        target: /app
      - ./deploy/bashrc:/root/.bashrc
    networks:
      freedom_net:
        ipv4_address: 172.16.110.4
    working_dir: /app/frontend
    command: /bin/bash /app/deploy/init_frontend
    environment:
      - DB_HOST=sm_postgres
      - DB_NAME=machine
      - DB_USER=user
      - DB_PASS=pass
  
  sm_backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sm_backend
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
      - ./deploy/bashrc:/root/.bashrc
    networks:
      freedom_net:
        ipv4_address: 172.16.110.5
    working_dir: /app/backend
    command: python3 manage.py runserver 172.16.110.5:80
    environment:
      - DEBUG=True
      - DB_HOST=sm_postgres
      - DB_NAME=machine
      - DB_USER=user
      - DB_PASS=pass
      - DB_PORT=5432
    depends_on:
      - sm_postgres
      - sm_nginx
      - sm_frontend

  sm_crawler_1:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sm_crawler_1
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
      - ./deploy/bashrc:/root/.bashrc
    networks:
      freedom_net:
        ipv4_address: 172.16.110.6
    working_dir: /app/crawler
    command: python3 bot.py --start_url=https://slovardalja.net --crawler_name=crawler_1
    environment:
      - DB_HOST=sm_postgres
      - DB_NAME=machine
      - DB_USER=user
      - DB_PASS=pass
      - DB_PORT=5432
    depends_on:
      - sm_postgres

  sm_crawler_2:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sm_crawler_2
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
      - ./deploy/bashrc:/root/.bashrc
    networks:
      freedom_net:
        ipv4_address: 172.16.110.7
    working_dir: /app/crawler
    command: python3 bot.py --start_url=https://wooordhunt.ru/dic/content/ru_en --crawler_name=crawler_2
    environment:
      - DB_HOST=sm_postgres
      - DB_NAME=machine
      - DB_USER=user
      - DB_PASS=pass
      - DB_PORT=5432
    depends_on:
      - sm_postgres

  sm_crawler_3:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sm_crawler_3
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
      - ./deploy/bashrc:/root/.bashrc
    networks:
      freedom_net:
        ipv4_address: 172.16.110.8
    working_dir: /app/crawler
    command: python3 bot.py --start_url=https://mail.ru --crawler_name=crawler_3
    environment:
      - DB_HOST=sm_postgres
      - DB_NAME=machine
      - DB_USER=user
      - DB_PASS=pass
      - DB_PORT=5432
    depends_on:
      - sm_postgres

networks:
  freedom_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.110.0/24
        gateway: 172.16.110.1