version: '3.9'

services:

  sm_postgres:
    image: postgres:13
    container_name: sm_postgres
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
    networks:
      freedom_net:
        ipv4_address: 172.16.110.2
    working_dir: /app
    environment:
      POSTGRES_DB: machine
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGPASSWORD: pass
    ports:
      - 5432:5432
  
  sm_nginx:
    image: nginx:latest
    container_name: sm_nginx
    restart: always
    networks:
      freedom_net:
        ipv4_address: 172.16.110.3
    volumes:
      - type: bind
        source: ./
        target: /app
      - ./docker/docker-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/hosts:/etc/hosts
      - ./docker/bashrc:/root/.bashrc
    ports:
      - 8000:80
  
  sm_backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sm_backend
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
      - ./docker/bashrc:/root/.bashrc
    networks:
      freedom_net:
        ipv4_address: 172.16.110.5
    working_dir: /app/backend
    command: /venv/bin/python3 manage.py runserver 172.16.110.5:80
    environment:
      - DEBUG=True
      - DB_HOST=sm_postgres
      - DB_NAME=machine
      - DB_USER=user
      - DB_PASS=pass
      - DB_PORT=5432
    depends_on:
      - sm_postgres
      - sm_nginx

  sm_crawler_1:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sm_crawler_1
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
      - ./docker/bashrc:/root/.bashrc
    networks:
      freedom_net:
        ipv4_address: 172.16.110.6
    working_dir: /app/crawler
    command: /venv/bin/python3 bot.py --start_url=https://omfil.ru/
    environment:
      - DB_HOST=sm_postgres
      - DB_NAME=machine
      - DB_USER=user
      - DB_PASS=pass
      - DB_PORT=5432
    depends_on:
      - sm_postgres

  sm_i2pd:
    image: purplei2p/i2pd
    container_name: sm_i2pd
    restart: always
    networks:
      freedom_net:
        ipv4_address: 172.16.110.9
    volumes:
      - ./docker/i2pd-tunnels.conf:/etc/i2pd/tunnels.conf
    ports:
      - 7071:7070

networks:
  freedom_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.110.0/24
        gateway: 172.16.110.1