version: '3.9'

services:

  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
      - postgres-data:/var/lib/postgresql/data
    networks:
      freedom_net:
        ipv4_address: 172.16.238.2
    environment:
      POSTGRES_DB: freedom
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      PGPASSWORD: django
    ports:
      - 5432:5432
  
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    networks:
      freedom_net:
        ipv4_address: 172.16.238.3
    volumes:
      - type: bind
        source: ./
        target: /app
      - ./deploy/docker-nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
  
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: backend
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
    networks:
      freedom_net:
        ipv4_address: 172.16.238.4
    working_dir: /app/backend
    command: python3 manage.py runserver 0.0.0.0:80
    environment:
      - FREEDOM_DEBUG=True
      - FREEDOM_DB_HOST=postgres
      - FREEDOM_DB_NAME=freedom
      - FREEDOM_DB_USER=django
      - FREEDOM_DB_PASS=django
      - FREEDOM_DB_PORT=5432
    depends_on:
      - postgres
      - nginx
  
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: frontend
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
    networks:
      freedom_net:
        ipv4_address: 172.16.238.5
    working_dir: /app/frontend
    command: gulp # TODO: GULP
    environment:
      - DB_HOST=postgres
      - DB_NAME=freedom
      - DB_USER=django
      - DB_PASS=django
    depends_on:
      - nginx

  spyder_1:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: spyder
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
    networks:
      freedom_net:
        ipv4_address: 172.16.238.6
    working_dir: /app/spyder
    command: cat /dev/zero # python3 bot.py --start_url=https://ru.wikipedia.org/wiki/Заглавная_страница --spyder_name=spyder_1
    environment:
      - DB_HOST=postgres
      - DB_NAME=freedom
      - DB_USER=django
      - DB_PASS=django
    depends_on:
      - postgres
      - nginx

  spyder_2:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: spyder
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
    networks:
      freedom_net:
        ipv4_address: 172.16.238.7
    working_dir: /app/spyder
    command: python3 bot.py --start_url=https://mail.ru --spyder_name=spyder_2
    environment:
      - DB_HOST=postgres
      - DB_NAME=freedom
      - DB_USER=django
      - DB_PASS=django
    depends_on:
      - postgres
      - nginx

  spyder_3:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: spyder
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
    networks:
      freedom_net:
        ipv4_address: 172.16.238.8
    working_dir: /app/spyder
    command: python3 bot.py --start_url=https://petrosian.ru --spyder_name=spyder_2
    environment:
      - DB_HOST=postgres
      - DB_NAME=freedom
      - DB_USER=django
      - DB_PASS=django
    depends_on:
      - postgres
      - nginx

volumes:
  postgres-data:

networks:
  freedom_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1