version: '3.9'

services:

  sm_postgres:
    image: postgres:13
    container_name: sm_postgres
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
    networks:
      freedom_net:
        ipv4_address: 172.16.110.2
    working_dir: /app
    environment:
      POSTGRES_DB: machine
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGPASSWORD: pass
    ports:
      - 5432:5432
  
  sm_nginx:
    image: nginx:latest
    container_name: sm_nginx
    restart: always
    networks:
      freedom_net:
        ipv4_address: 172.16.110.3
    volumes:
      - type: bind
        source: ./
        target: /app
      - ./deploy/docker-nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
  
  sm_backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sm_backend
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
    networks:
      freedom_net:
        ipv4_address: 172.16.110.4
    working_dir: /app/backend
    command: python3 manage.py runserver 172.16.110.4:80
    environment:
      - DEBUG=True
      - DB_HOST=sm_postgres
      - DB_NAME=machine
      - DB_USER=user
      - DB_PASS=pass
      - DB_PORT=5432
    depends_on:
      - sm_postgres
      - sm_nginx
  
  sm_frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sm_frontend
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
    networks:
      freedom_net:
        ipv4_address: 172.16.110.5
    working_dir: /app/frontend
    command: gulp # TODO: GULP
    environment:
      - DB_HOST=sm_postgres
      - DB_NAME=machine
      - DB_USER=user
      - DB_PASS=pass
    depends_on:
      - sm_backend

  sm_spyder_1:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sm_spyder_1
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
    networks:
      freedom_net:
        ipv4_address: 172.16.110.6
    working_dir: /app/spyder
    command: python3 bot.py --start_url=https://mail.ru --spyder_name=spyder_1
    environment:
      - DB_HOST=sm_postgres
      - DB_NAME=machine
      - DB_USER=user
      - DB_PASS=pass
      - DB_PORT=5432
    depends_on:
      - sm_postgres

  sm_spyder_2:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sm_spyder_2
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
    networks:
      freedom_net:
        ipv4_address: 172.16.110.7
    working_dir: /app/spyder
    command: python3 bot.py --start_url=https://ru.wikipedia.org/wiki/Заглавная_страница --spyder_name=spyder_2
    environment:
      - DB_HOST=sm_postgres
      - DB_NAME=machine
      - DB_USER=user
      - DB_PASS=pass
      - DB_PORT=5432
    depends_on:
      - sm_postgres

  sm_spyder_3:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sm_spyder_3
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /app
    networks:
      freedom_net:
        ipv4_address: 172.16.110.8
    working_dir: /app/spyder
    command: python3 bot.py --start_url=https://petrosian.ru --spyder_name=spyder_3
    environment:
      - DB_HOST=sm_postgres
      - DB_NAME=machine
      - DB_USER=user
      - DB_PASS=pass
      - DB_PORT=5432
    depends_on:
      - sm_postgres

networks:
  freedom_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.110.0/24
        gateway: 172.16.110.1