# Generated by Django 4.1.5 on 2023-01-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['url'], 'verbose_name': 'Домен', 'verbose_name_plural': 'Все известные домены'},
        ),
        migrations.AlterModelOptions(
            name='domainsqueue',
            options={'ordering': ['url'], 'verbose_name': 'Домен', 'verbose_name_plural': 'Очередь на индексацию'},
        ),
        migrations.AlterField(
            model_name='domainsqueue',
            name='spyder_name',
            field=models.TextField(default=None, null=True, verbose_name='Имя паука'),
        ),
    ]
